### ISSUE TITLE
Component reference is lost when outsideClickHandler is executed

### ISSUE THREAD

**Issue by myassir** [willmendesneto/ngx-page-click#8]
**I'm submitting a

- [ ] bug report => search github for a similar issue or PR before submitting
- [x] feature request

**Current behavior**

The click handler is executed with the reference of NgxPageClickComponent

**Expected behavior**

It will be better to execute the handler with the calling component reference instead.

**Reproduction of the problem**
```
export class MyComponent implements OnInit{
   // some code
   myMethod(){
      // some code
   }
   outsideClickHandler(){
       // here myMethod will not be called
        this.myMethod();
    }
}
```

**Comment by willmendesneto** [comment]
Hi @myassir, thank you so much for raising this issue!

Looks like your code sample is not binding `this` into it. This is necessary because the component needs the current scope to call it. As an example of what I'm talking about, you can add the scope into `outsideClickHandler` using 2 approaches:

#1. by adding this via `.bind()` method

```javascript
export class MyComponent {
  constructor() {
    // You can add the this scope via binding `this` into the function
    // like it's used on `outsideClickHandler()` method
    this.outsideClickHandler = this.outsideClickHandler.bind(this);
  }

  outsideClickHandler() {
    alert('CLICK OUTSIDE TRIGGERED FOR FIRST CONTENT');
  }
}
```

#2. By using arrow functions on `outsideClickHandler()` method

```javascript
export class MyComponent {
  private myPrivateMethod() {
    alert('CLICK OUTSIDE TRIGGERED FOR SECOND CONTENT');
  }

  // You can add the this scope via arrow function
  // like it's used on `outsideClickHandler2()` method
  // As you can see, it calls the private method `myPrivateMethod`
  outsideClickHandler2 = () => {
    this.myPrivateMethod();
  }
}
```

You can also check this live demo working with these approaches on the Stackblitz demo in this link https://stackblitz.com/edit/ngx-page-click-sample?file=app%2Fapp.component.ts

I'm closing this issue for now, but feel free to open it again if you think it's not solved 👋
